### PR TITLE
Upgrade to libgmp 6.1.1; version 2.0.0

### PR DESCRIPTION
**Pull request by dragonsinth**

### CODE REVIEW

**Comment by dragonsinth** [comment]
So this is interesting.

- My Ubuntu binary (b3f6dda) won't run on CentOS
- My CentOS binary (8ee3c81) will run on Ubuntu
- Neither seems to run on Travis :(

**Comment by dragonsinth** [comment]
@dekobon

**Comment by dekobon** [comment]
If this works, then let's rebuild the Solaris binary with the new Makefile as well.

**Comment by dragonsinth** [comment]
Wow, so that fixed it!  For the uninitiated, do you know what change in the Makefile is responsible for the fix?  I assume it wasn't debug symbols.

**Comment by dekobon** [comment]
When I built without a modified makefile on the Google VM, it built a binary that worked on my Linux workstation. I think there was something wrong with the binary that was generated in the initial build, but I'm not sure what the root cause was.

The notable changes are:
Running configure with the following flags:
```
--enable-fat --enable-alloca=malloc-reentrant --disable-static
```
You can find documentation on them [here](https://gmplib.org/manual/Build-Options.html).

My rationale for enabling fat binaries is that is was a default option when compiling on x86 when I looked at the [Debian package configuration](https://anonscm.debian.org/viewvc/debian-science/packages/gmp/trunk/debian/rules?view=markup).

My rationale for enabling malloc-reentrant was that it was the only temporary memory allocation scheme documented that was thread safe.

My rationale for disabling static binaries was that JNA requires shared (dynamic) libraries and they aren't being installed, so I see no reason to even build them.

**Comment by dragonsinth** [comment]
Those all sound great.  Although the doc for `--enable-alloca` has this to say:

```
‘reentrant’ - alloca if available, otherwise ‘malloc-reentrant’. This is the default.
[...]
alloca is reentrant and fast, and is recommended. It actually allocates just small blocks on the stack; larger ones use malloc-reentrant.
```

Seems like we'd want `reentrant` for performance reasons rather than always allocating on the heap?

**Comment by dekobon** [comment]
Yes, we totally want the default value for that. Let's deleted that from the configure line. I misread the documentation.

**Comment by dragonsinth** [comment]
Giving that a whirl now

**Comment by dragonsinth** [comment]
Boom.  Okay, I'm going to respin binaries on all these platforms and get a good series of commits merged into master.

Thanks a ton!!!

**Comment by dragonsinth** [comment]
@dekobon mac and linux rebuilt, would you like to provide the sunos binary?

**Comment by dragonsinth** [comment]
I think this is really ready to merge now.

@dekobon and @batmaninpink does it look good to you?

**Comment by dekobon** [comment]
Let me get in the Makefile change and well go for it.

**Comment by batmaninpink** [comment]
`CFLAGS=-g` might not be what we want since this was for performance increase to start with

**Comment by dekobon** [comment]
We may want the [-Og flag](http://stackoverflow.com/a/24117136/33611). I'm *very* cautions of releasing binaries without debugging symbols because it makes debugging problems with production systems quite hard.

**Comment by dragonsinth** [comment]
Seems like it should be possible to have some debugging symbols in without destroying optimizations.  Anyone care to test the performance and compare benchmarks?

Might be worth comparing:
- no extra flags
- -g
- -Og
- -g -O2

It may not have a large effect since a lot of the inner loops are hand written assembly.

**Comment by dekobon** [comment]
What is the best way to run a benchmark? I found this: https://gmplib.org/gmpbench.html
Or would it be best to benchmark it via the JNA interfaces?
Also, if we want to benchmark it on a cloud service, we will need to run it a bunch of times because instances are on shared compute nodes and will see very different results when looking at these types of microbenchmarks.

**Comment by dragonsinth** [comment]
I was just planning to run the Java benchmarks when I get a chance if no one's gotten to it before me.

**Comment by dragonsinth** [comment]
Here are some raw results I got on my Mac.  Doesn't seem to make much difference for me.
-Og wasn't supported for me on Mac so I didn't test that.

```
No flags
------------
Testing 40000 512-bit private rsa's NativeInsecure
40000 512-bit private rsa's in 1.931s
20714.66 ops/s
Testing 8000 1024-bit private rsa's NativeInsecure
8000 1024-bit private rsa's in 1.446s
5532.50 ops/s
Testing 1600 2048-bit private rsa's NativeInsecure
1600 2048-bit private rsa's in 2.147s
745.23 ops/s

Testing 30000 512-bit private rsa's NativeSecure
30000 512-bit private rsa's in 1.561s
19218.45 ops/s
Testing 6000 1024-bit private rsa's NativeSecure
6000 1024-bit private rsa's in 1.38s
4347.83 ops/s
Testing 1200 2048-bit private rsa's NativeSecure
1200 2048-bit private rsa's in 1.77s
677.97 ops/s


Using -g
------------
Testing 40000 512-bit private rsa's NativeInsecure
40000 512-bit private rsa's in 1.682s
23781.21 ops/s
Testing 8000 1024-bit private rsa's NativeInsecure
8000 1024-bit private rsa's in 1.35s
5925.93 ops/s
Testing 1600 2048-bit private rsa's NativeInsecure
1600 2048-bit private rsa's in 1.856s
862.07 ops/s

Testing 30000 512-bit private rsa's NativeSecure
30000 512-bit private rsa's in 1.439s
20847.81 ops/s
Testing 6000 1024-bit private rsa's NativeSecure
6000 1024-bit private rsa's in 1.29s
4651.16 ops/s
Testing 1200 2048-bit private rsa's NativeSecure
1200 2048-bit private rsa's in 1.648s
728.16 ops/s


Using -g -O2
------------
Testing 40000 512-bit private rsa's NativeInsecure
40000 512-bit private rsa's in 1.577s
25364.62 ops/s
Testing 8000 1024-bit private rsa's NativeInsecure
8000 1024-bit private rsa's in 1.327s
6028.64 ops/s
Testing 1600 2048-bit private rsa's NativeInsecure
1600 2048-bit private rsa's in 1.835s
871.93 ops/s

Testing 30000 512-bit private rsa's NativeSecure
30000 512-bit private rsa's in 1.398s
21459.23 ops/s
Testing 6000 1024-bit private rsa's NativeSecure
6000 1024-bit private rsa's in 1.339s
4480.96 ops/s
Testing 1200 2048-bit private rsa's NativeSecure
1200 2048-bit private rsa's in 1.736s
691.24 ops/s


Using -O2
------------
Testing 40000 512-bit private rsa's NativeInsecure
40000 512-bit private rsa's in 1.55s
25806.45 ops/s
Testing 8000 1024-bit private rsa's NativeInsecure
8000 1024-bit private rsa's in 1.309s
6111.54 ops/s
Testing 1600 2048-bit private rsa's NativeInsecure
1600 2048-bit private rsa's in 1.922s
832.47 ops/s

Testing 30000 512-bit private rsa's NativeSecure
30000 512-bit private rsa's in 1.452s
20661.16 ops/s
Testing 6000 1024-bit private rsa's NativeSecure
6000 1024-bit private rsa's in 1.247s
4811.55 ops/s
Testing 1200 2048-bit private rsa's NativeSecure
1200 2048-bit private rsa's in 1.683s
713.01 ops/s
```

**Comment by dragonsinth** [comment]
Something to consider, I stripped out the explicit setting of CFLAGS and ran a build with the default configure, and I noticed these seem to be the in default CFLAGS: `-O2 -pedantic -fomit-frame-pointer -m64` which all get replaced if we try to set any explicit flags.

Contrast a run with CFLAGS='-g'

```
gcc -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_dcpi1_divappr_q -g -c dcpi1_divappr_q.c  -fno-common -DPIC -o .libs/dcpi1_divappr_q.o
```

with a stock run

```
gcc -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_divrem -O2 -pedantic -fomit-frame-pointer -m64 -c divrem.c  -fno-common -DPIC -o .libs/divrem.o
```

Honestly, this makes me want to not set explicit CFLAGS and trust the libgmp folks picked reasonable defaults.

**Comment by batmaninpink** [comment]
Yeah don't mess with the CFLAGS... I ran a quick benchmark:

GMPbench/rsa (CFLAGS=-g): 6980.3
GMPbench/rsa (stock CFLAGS): 7598.8

**Comment by dragonsinth** [comment]
Alright, I'm going to re-spin things without CFLAGS.

**Comment by dekobon** [comment]
For what it is worth, I just did a benchmark of modpow operations as used in RSA signing. I pitted jnagmp 1.1.0 against the new branch with debug symbols and a version without any CFLAGS set. I see no noticeable difference (at millisecond resolution) in performance for the 100k or so operations that I've tried.

I don't know what everyone else is using GMP for, but [modpow for RSA done in Java](https://github.com/joyent/java-http-signature/blob/master/common/src/main/java/com/joyent/http/signature/crypto/MantaNativeRSACoreEngine.java) was my primary use case.

**Comment by dragonsinth** [comment]
Is there some way to get configure to just add `-g` to the existing default CFLAGS without completely overwriting them?  I'd feel more comfortable if we could do that.

**Comment by dekobon** [comment]
Yup we can do that. I also asked some of the C experts at Joyent about this and this is what they had to say. This would preserve the other optimization flags. I'll have a PR out in a jiffy.

**Comment by dekobon** [comment]
I just read through the configure.ac. It is best that we don't set -g. Could you just delete the CFLAGS line and respin?

**Comment by dragonsinth** [comment]
Will do.

**Comment by dragonsinth** [comment]
@JakeWharton I think we're ready to do a 2.0.0 release.  Are you still the right trigger man for that?  I prepped CHANGELOG.md, but you'll need to fill in the exact release date.

**Comment by dragonsinth** [comment]
Many thanks to everyone who contributed to this release!  In no particular order:

@dekobon 
@batmaninpink 
@jacobwil 
@ruescasd 
@wilko77

I think 2.0.0 is gonna be great.

**Comment by JakeWharton** [comment]
Yep. Will do tonight or at worst tomorrow.

**Comment by JakeWharton** [comment]
Released!

**Comment by dragonsinth** [comment]
Thanks @JakeWharton !!

**Pull request merged**
