### PR TITLE
Added support for Solaris 10/SmartOS/Illumos x86-64 support.

### PR DESCRIPTION
**Pull request by dekobon**
I've added support for a Solaris 10 compatible binary. I compiled and tested on SmartOS. The other change is that I removed the global else statement in the Makefile, such that if the OS is not recognized it fails.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Hi @dekobon. Can you please [sign the CLA][1] so that, assuming the changes are approved, we can merge?

 [1]: http://squ.re/sign-the-cla

**Comment by dekobon** [comment]
Hi @JakeWharton,

I've signed the CLA.
Thanks!

**Comment by dekobon** [comment]
@JakeWharton Can I help with any work needed to merge this PR?

**Comment by JakeWharton** [comment]
@jhump or @dragonsinth would have to help there. I'm just the human version of a CLA checking robot :cry:

**Comment by dragonsinth** [comment]
Hi @dekobon, thanks for the contribution.  The Makefile changes LGTM.

However.. I'm really unsure about how to proceed with accepting a binary submission.  I don't doubt that it's legit, but I have no way to verify it. Are there any public OS images I could run on GCE to compile the binary myself?

**Comment by dekobon** [comment]
Hi @dragonsinth ,

I can provide you a host on the Joyent public cloud. Please email with your prefered email address and send me your public key. My email is elijah.zupancic@joyent.com

**Comment by dragonsinth** [comment]
This is now merged, thanks @dekobon.  I built the binary, ran the tests, and committed to master.  I did need to make a small Makefile tweak, but no biggie.

**Comment by dekobon** [comment]
@JakeWharton - I hear that you were the person to ask about getting a release pushed to Maven Central. Is there any chance you can help to make that happen?

**Comment by JakeWharton** [comment]
Yep. I'll do it later tonight.

**Comment by JakeWharton** [comment]
Released as 1.1.0.

**Pull request closed without merging**
